# Generated by Django 6.0.5 on 2026-05-23 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Kundali",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                ("date_of_birth", models.DateField()),
                ("time_of_birth", models.TimeField()),
                ("place_of_birth", models.CharField(blank=True, max_length=255)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("meta", models.JSONField(default=dict)),
                ("kundali_data", models.JSONField(default=dict)),
                ("chart_data", models.JSONField(default=dict)),
                ("ashtakvarga", models.JSONField(default=dict)),
                ("dasha", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kundalis",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Kundali",
                "verbose_name_plural": "Kundalis",
                "ordering": ["-created_at"],
            },
        ),
    ]
